In [1]:
import numpy
firstArray = numpy.empty([4,2], dtype = numpy.uint16)
print("Printing Array")
print(firstArray)
print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[42964  1758]
 [13836 63377]
 [38837 15450]
 [24922 20625]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


In [7]:
import numpy as np
n = 3
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M)
flattened_M = M.flatten()
print("Converted matrix into a 1-dimensional array")
print(flattened_M)
mean_M = np.mean(flattened_M)
std_M = np.std(flattened_M)
z = (flattened_M - mean_M) / std_M
mean_z = np.mean(z)
std_z = np.std(z)
print("Mean of M: ", mean_M)
print("Mean of z: ", mean_z)
print("Standard deviation of M: ", std_M)
print("Standard deviation of z: ", std_z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Converted matrix into a 1-dimensional array
[1 2 3 4 5 6 7 8 9]
Mean of M:  5.0
Mean of z:  0.0
Standard deviation of M:  2.581988897471611
Standard deviation of z:  1.0


In [5]:
import numpy as np
arr1=np.array([[1,2,3],[44,65,32],[65,12,7]])
print(arr1)
min1=np.amin(arr1,1)
print(min1)
max1=np.amax(arr1,0)
print(max1)


[[ 1  2  3]
 [44 65 32]
 [65 12  7]]
[ 1 32  7]
[65 65 32]


In [6]:
import numpy as np
def create_array(n):
    return [[i + j for j in range(n)] for i in range(n)]
print(create_array(3))

[[0, 1, 2], [1, 2, 3], [2, 3, 4]]
